# CodeRabbit Configuration
# https://docs.coderabbit.ai/guides/configure-coderabbit

language: "en"

early_access: false

reviews:
  # Enable auto-review for PRs
  profile: "chill"
  request_changes_workflow: false
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - main
      - develop

  # Path-based instructions
  path_instructions:
    - path: "apps/api/**/*.py"
      instructions: |
        Review Python backend code for:
        - FastAPI best practices
        - SQLAlchemy query efficiency
        - Proper error handling with Sentry
        - Rate limiting and security considerations

    - path: "apps/web/**/*.tsx"
      instructions: |
        Review React/Next.js frontend code for:
        - React hooks best practices
        - Proper TypeScript typing
        - Accessibility (a11y) compliance
        - Dark mode support
        - i18n/localization

    - path: "scripts/**/*.ts"
      instructions: |
        Review automation scripts for:
        - Error handling
        - Environment variable usage
        - Output format consistency with PatchTask schema

  # Ignore patterns for review
  path_filters:
    - "!**/*.lock"
    - "!**/package-lock.json"
    - "!**/*.min.js"
    - "!**/node_modules/**"
    - "!**/__pycache__/**"
    - "!**/dist/**"
    - "!**/build/**"
    - "!**/.next/**"

chat:
  auto_reply: true
