// Generated by scripts/generate_web_patterns.py. Do not edit manually.

export type GeneratedSafetyPattern = {
  readonly name: string;
  readonly category: string;
  readonly source: string;
  readonly detectionFlags: string;
  readonly redactionFlags: string;
  readonly enabledInDetection: boolean;
  readonly enabledInRedaction: boolean;
  readonly replacement: string;
  readonly validator?: "luhn";
};

export type CompiledSafetyPattern = {
  readonly pattern: GeneratedSafetyPattern;
  readonly regex: RegExp;
};

export const GENERATED_SAFETY_PATTERN_VERSION = 1 as const;

export const GENERATED_SAFETY_PATTERNS: readonly GeneratedSafetyPattern[] = [
  {
    "name": "token_url",
    "category": "token",
    "source": "https?://[^\\s]+[?&](?:token|key|secret|api_key|access_token|auth)=[^\\s&]+",
    "detectionFlags": "i",
    "redactionFlags": "ig",
    "enabledInDetection": true,
    "enabledInRedaction": true,
    "replacement": "[REDACTED_URL]"
  },
  {
    "name": "bearer_token",
    "category": "token",
    "source": "Bearer\\s+[A-Za-z0-9._~+/=-]+",
    "detectionFlags": "i",
    "redactionFlags": "ig",
    "enabledInDetection": true,
    "enabledInRedaction": true,
    "replacement": "[REDACTED_TOKEN]"
  },
  {
    "name": "jwt",
    "category": "token",
    "source": "\\beyJ[A-Za-z0-9_-]+\\.[A-Za-z0-9_-]+\\.[A-Za-z0-9_-]+\\b",
    "detectionFlags": "",
    "redactionFlags": "g",
    "enabledInDetection": true,
    "enabledInRedaction": true,
    "replacement": "[REDACTED_TOKEN]"
  },
  {
    "name": "secret_assignment",
    "category": "secret",
    "source": "(?:PASSWORD|SECRET|API_KEY|APIKEY|ACCESS_TOKEN|AUTH_TOKEN|PRIVATE_KEY|SECRET_KEY|ENCRYPTION_KEY)\\s*[=:]\\s*\\S+",
    "detectionFlags": "i",
    "redactionFlags": "ig",
    "enabledInDetection": true,
    "enabledInRedaction": true,
    "replacement": "[REDACTED_SECRET]"
  },
  {
    "name": "openai_project_key",
    "category": "provider_key",
    "source": "sk-proj-[A-Za-z0-9-]{20,}",
    "detectionFlags": "",
    "redactionFlags": "g",
    "enabledInDetection": true,
    "enabledInRedaction": true,
    "replacement": "[REDACTED_API_KEY]"
  },
  {
    "name": "anthropic_key",
    "category": "provider_key",
    "source": "sk-ant-[A-Za-z0-9-]{20,}",
    "detectionFlags": "",
    "redactionFlags": "g",
    "enabledInDetection": true,
    "enabledInRedaction": true,
    "replacement": "[REDACTED_API_KEY]"
  },
  {
    "name": "openai_key",
    "category": "provider_key",
    "source": "sk-[A-Za-z0-9]{20,}",
    "detectionFlags": "",
    "redactionFlags": "g",
    "enabledInDetection": true,
    "enabledInRedaction": true,
    "replacement": "[REDACTED_API_KEY]"
  },
  {
    "name": "google_key",
    "category": "provider_key",
    "source": "AIza[A-Za-z0-9_-]{30,}",
    "detectionFlags": "",
    "redactionFlags": "g",
    "enabledInDetection": true,
    "enabledInRedaction": true,
    "replacement": "[REDACTED_API_KEY]"
  },
  {
    "name": "groq_key",
    "category": "provider_key",
    "source": "gsk_[A-Za-z0-9]{20,}",
    "detectionFlags": "",
    "redactionFlags": "g",
    "enabledInDetection": true,
    "enabledInRedaction": true,
    "replacement": "[REDACTED_API_KEY]"
  },
  {
    "name": "xai_key",
    "category": "provider_key",
    "source": "xai-[A-Za-z0-9]{20,}",
    "detectionFlags": "",
    "redactionFlags": "g",
    "enabledInDetection": true,
    "enabledInRedaction": true,
    "replacement": "[REDACTED_API_KEY]"
  },
  {
    "name": "email",
    "category": "pii",
    "source": "\\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}\\b",
    "detectionFlags": "i",
    "redactionFlags": "ig",
    "enabledInDetection": true,
    "enabledInRedaction": true,
    "replacement": "[REDACTED_EMAIL]"
  },
  {
    "name": "phone",
    "category": "pii",
    "source": "(?:\\+\\d{1,3}[-.\\s]?)?(?:\\(\\d{3}\\)|\\b\\d{3})[-.\\s]?\\d{3}[-.\\s]?\\d{4}\\b",
    "detectionFlags": "",
    "redactionFlags": "g",
    "enabledInDetection": true,
    "enabledInRedaction": true,
    "replacement": "[REDACTED_PHONE]"
  },
  {
    "name": "card_candidate",
    "category": "payment_card",
    "source": "\\b(?:\\d[ -]?){12,18}\\d\\b",
    "detectionFlags": "",
    "redactionFlags": "g",
    "enabledInDetection": true,
    "enabledInRedaction": true,
    "replacement": "[REDACTED_CC]",
    "validator": "luhn"
  }
];

export function createDetectionPatterns(): readonly CompiledSafetyPattern[] {
  return GENERATED_SAFETY_PATTERNS
    .filter((pattern) => pattern.enabledInDetection)
    .map((pattern) => ({ pattern, regex: new RegExp(pattern.source, pattern.detectionFlags) }));
}

export function createRedactionPatterns(): readonly CompiledSafetyPattern[] {
  return GENERATED_SAFETY_PATTERNS
    .filter((pattern) => pattern.enabledInRedaction)
    .map((pattern) => ({ pattern, regex: new RegExp(pattern.source, pattern.redactionFlags) }));
}
