import Link from "next/link";
import { getServerTranslations } from "@/lib/i18n/server";

export default async function TermsPage() {
    const { t } = await getServerTranslations();

    return (
        <main className="min-h-screen bg-gradient-to-br from-amber-50 via-[#fff7eb] to-[#f8e6c2] px-6 py-16">
            <div className="mx-auto max-w-4xl space-y-8">
                <header className="space-y-4 text-center">
                    <h1 className="text-4xl font-bold text-[#3a2a1a]">{t("pages.terms.title")}</h1>
                </header>

                <div className="rounded-3xl border border-amber-100/80 bg-white/90 p-8 shadow-lg text-[#5a4a3a] space-y-6">
                    <section className="space-y-2">
                        <h2 className="text-xl font-semibold text-[#3a2a1a]">1. Service Description</h2>
                        <p>Consultaion is an AI-powered debate and simulation platform. We provide tools to simulate multi-agent debates on various topics using large language models.</p>
                    </section>

                    <section className="space-y-2">
                        <h2 className="text-xl font-semibold text-[#3a2a1a]">2. Accounts & Usage</h2>
                        <ul className="list-disc pl-5 space-y-1">
                            <li>You must be at least 18 years old to use this service.</li>
                            <li>You are responsible for maintaining the security of your account.</li>
                            <li>You agree not to use the platform for illegal, harmful, or abusive purposes.</li>
                            <li>We reserve the right to suspend or terminate accounts that violate these terms.</li>
                        </ul>
                    </section>

                    <section className="space-y-2">
                        <h2 className="text-xl font-semibold text-[#3a2a1a]">3. Plans & Quotas</h2>
                        <p>We offer Free and Pro plans with different usage limits:</p>
                        <ul className="list-disc pl-5 space-y-1">
                            <li><strong>Free Plan:</strong> Limited daily tokens and debates.</li>
                            <li><strong>Pro Plan:</strong> Higher limits and priority access.</li>
                            <li>Quotas reset daily. We reserve the right to modify plan limits with notice.</li>
                        </ul>
                    </section>

                    <section className="space-y-2">
                        <h2 className="text-xl font-semibold text-[#3a2a1a]">4. Disclaimers</h2>
                        <div className="bg-amber-50 p-4 rounded-lg border border-amber-200/50 text-sm">
                            <p><strong>AI Output Warning:</strong> The content generated by Consultaion is produced by Artificial Intelligence. It may contain errors, biases, or hallucinations. It should NOT be considered professional advice (legal, medical, financial, etc.). Always verify important information.</p>
                        </div>
                        <p className="text-stone-600">&quot;Terms of Service&quot; content coming soon. Please contact us for more information.</p>
                    </section>

                    <section className="space-y-2">
                        <h2 className="text-xl font-semibold text-[#3a2a1a]">5. Changes to Terms</h2>
                        <p>We may update these terms from time to time. Continued use of the service constitutes acceptance of the new terms.</p>
                    </section>

                    <section className="space-y-2">
                        <h2 className="text-xl font-semibold text-[#3a2a1a]">6. Governing Law</h2>
                        <p>These terms are governed by the laws of the jurisdiction in which Consultaion operates.</p>
                    </section>

                    <div className="pt-4 border-t border-amber-200/50 text-sm text-amber-900/60">
                        <p>Last Updated: December 2024</p>
                    </div>
                </div>

                <div className="text-center">
                    <Link
                        href="/"
                        className="inline-flex items-center text-sm font-semibold text-amber-700 underline-offset-4 hover:underline"
                    >
                        ← {t("pages.placeholder.backHome")}
                    </Link>
                </div>
            </div>
        </main>
    );
}
