#!/usr/bin/env python3
"""Generate browser-safe regex metadata from the safety pattern contract."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
API_ROOT = ROOT / "apps" / "api"
OUTPUT_PATH = ROOT / "apps" / "web" / "lib" / "generatedPatterns.ts"
sys.path.insert(0, str(API_ROOT))

from safety.patterns import SafetyPatternContract, load_pattern_contract  # noqa: E402


def render_typescript(contract: SafetyPatternContract) -> str:
    generated = []
    for pattern in contract.patterns:
        if pattern.platform != "shared":
            continue
        detection_flags = "i" if pattern.case_insensitive else ""
        redaction_flags = detection_flags + ("g" if pattern.global_for_redaction else "")
        generated.append(
            {
                "name": pattern.name,
                "category": pattern.category,
                "source": pattern.source,
                "detectionFlags": detection_flags,
                "redactionFlags": redaction_flags,
                "enabledInDetection": pattern.enabled_in_detection,
                "enabledInRedaction": pattern.enabled_in_redaction,
                "replacement": pattern.replacement,
                **({"validator": pattern.validator} if pattern.validator else {}),
            }
        )

    serialized = json.dumps(generated, ensure_ascii=True, indent=2)
    return f"""// Generated by scripts/generate_web_patterns.py. Do not edit manually.

export type GeneratedSafetyPattern = {{
  readonly name: string;
  readonly category: string;
  readonly source: string;
  readonly detectionFlags: string;
  readonly redactionFlags: string;
  readonly enabledInDetection: boolean;
  readonly enabledInRedaction: boolean;
  readonly replacement: string;
  readonly validator?: "luhn";
}};

export type CompiledSafetyPattern = {{
  readonly pattern: GeneratedSafetyPattern;
  readonly regex: RegExp;
}};

export const GENERATED_SAFETY_PATTERN_VERSION = {contract.version} as const;

export const GENERATED_SAFETY_PATTERNS: readonly GeneratedSafetyPattern[] = {serialized};

export function createDetectionPatterns(): readonly CompiledSafetyPattern[] {{
  return GENERATED_SAFETY_PATTERNS
    .filter((pattern) => pattern.enabledInDetection)
    .map((pattern) => ({{ pattern, regex: new RegExp(pattern.source, pattern.detectionFlags) }}));
}}

export function createRedactionPatterns(): readonly CompiledSafetyPattern[] {{
  return GENERATED_SAFETY_PATTERNS
    .filter((pattern) => pattern.enabledInRedaction)
    .map((pattern) => ({{ pattern, regex: new RegExp(pattern.source, pattern.redactionFlags) }}));
}}
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail when generated output is stale")
    args = parser.parse_args()

    expected = render_typescript(load_pattern_contract())
    if args.check:
        actual = OUTPUT_PATH.read_text(encoding="utf-8") if OUTPUT_PATH.exists() else ""
        if actual != expected:
            print(f"Generated safety patterns are stale: {OUTPUT_PATH}", file=sys.stderr)
            return 1
        return 0

    OUTPUT_PATH.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
