"""add_user_profile_fields

Revision ID: 409938eb0f98
Revises: 5744a0e5e5f7
Create Date: 2025-11-19 17:41:45.242803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '409938eb0f98'
down_revision: Union[str, None] = '5744a0e5e5f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    
    # Remove server defaults after creation if they shouldn't be there for new rows (optional, but cleaner)
    # SQLite doesn't support dropping defaults easily, but for boolean flags it's fine.

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('timezone')
        batch_op.drop_column('bio')
        batch_op.drop_column('avatar_url')
        batch_op.drop_column('display_name')
        batch_op.drop_column('is_admin')
        batch_op.drop_column('is_active')
    # ### end Alembic commands ###
