"""p135_coding_agent_models

Revision ID: 4cae97704905
Revises: p133_schema_drift_resolution
Create Date: 2026-06-21 08:10:10.933648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4cae97704905'
down_revision: Union[str, None] = 'p133_schema_drift_resolution'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coding_run',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('repo_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('branch', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('base_commit_sha', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('head_commit_sha', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('lane_config', sa.JSON(), nullable=True),
    sa.Column('file_paths', sa.JSON(), nullable=True),
    sa.Column('diff_preview', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coding_run_status'), 'coding_run', ['status'], unique=False)
    op.create_index(op.f('ix_coding_run_user_id'), 'coding_run', ['user_id'], unique=False)
    op.create_table('coding_turn',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('coding_run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['coding_run_id'], ['coding_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coding_turn_coding_run_id'), 'coding_turn', ['coding_run_id'], unique=False)
    op.create_index(op.f('ix_coding_turn_status'), 'coding_turn', ['status'], unique=False)
    op.create_table('coding_lane_result',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('coding_run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('coding_turn_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lane_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('token_usage', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['coding_run_id'], ['coding_run.id'], ),
    sa.ForeignKeyConstraint(['coding_turn_id'], ['coding_turn.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coding_run_id', 'coding_turn_id', 'lane_name', name='uq_coding_lane_result_lane')
    )
    op.create_table('coding_patch_artifact',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('coding_run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('coding_turn_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('final_patch', sa.Text(), nullable=False),
    sa.Column('apply_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('test_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('test_output', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['coding_run_id'], ['coding_run.id'], ),
    sa.ForeignKeyConstraint(['coding_turn_id'], ['coding_turn.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coding_run_id', 'coding_turn_id', name='uq_coding_patch_artifact_turn')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coding_patch_artifact')
    op.drop_table('coding_lane_result')
    op.drop_index(op.f('ix_coding_turn_status'), table_name='coding_turn')
    op.drop_index(op.f('ix_coding_turn_coding_run_id'), table_name='coding_turn')
    op.drop_table('coding_turn')
    op.drop_index(op.f('ix_coding_run_user_id'), table_name='coding_run')
    op.drop_index(op.f('ix_coding_run_status'), table_name='coding_run')
    op.drop_table('coding_run')
    # ### end Alembic commands ###
