"""add_debate_lease_fields

Revision ID: a5ca64b21960
Revises: 1187c6c5915d
Create Date: 2025-12-13 16:34:41.467627

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a5ca64b21960"
down_revision: Union[str, None] = "1187c6c5915d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("admin_event",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("level", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column("message", sa.Text(), nullable=False),
    sa.Column("trace_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column("debate_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column("meta", sa.JSON(), nullable=True),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_index("ix_admin_event_created_at", "admin_event", ["created_at"], unique=False)
    op.create_index(op.f("ix_admin_event_debate_id"), "admin_event", ["debate_id"], unique=False)
    op.create_index(op.f("ix_admin_event_level"), "admin_event", ["level"], unique=False)
    op.create_index(op.f("ix_admin_event_trace_id"), "admin_event", ["trace_id"], unique=False)
    op.create_table("support_note",
    sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column("author_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column("note", sa.Text(), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(["author_id"], ["user.id"], ),
    sa.ForeignKeyConstraint(["user_id"], ["user.id"], ),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_index(op.f("ix_support_note_author_id"), "support_note", ["author_id"], unique=False)
    op.create_index(op.f("ix_support_note_user_id"), "support_note", ["user_id"], unique=False)
    op.create_table("debate_error",
    sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column("debate_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column("error_summary", sa.Text(), nullable=False),
    sa.Column("participant_errors", sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(["debate_id"], ["debate.id"], ),
    sa.ForeignKeyConstraint(["user_id"], ["user.id"], ),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_index(op.f("ix_debate_error_debate_id"), "debate_error", ["debate_id"], unique=False)
    op.create_index(op.f("ix_debate_error_status"), "debate_error", ["status"], unique=False)
    op.create_index(op.f("ix_debate_error_user_id"), "debate_error", ["user_id"], unique=False)
    op.alter_column("billing_plans", "id",
               existing_type=sa.VARCHAR(length=36),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.drop_index("uq_billing_plans_slug", table_name="billing_plans")
    op.alter_column("billing_subscriptions", "id",
               existing_type=sa.VARCHAR(length=36),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.alter_column("billing_subscriptions", "plan_id",
               existing_type=sa.VARCHAR(length=36),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.alter_column("billing_usage", "id",
               existing_type=sa.VARCHAR(length=36),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.alter_column("billing_usage", "tokens_used",
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text("0"))
    op.add_column("debate", sa.Column("runner_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column("debate", sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("debate", sa.Column("last_heartbeat_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("debate", sa.Column("run_attempt", sa.Integer(), nullable=False))
    op.create_index(op.f("ix_debate_runner_id"), "debate", ["runner_id"], unique=False)
    op.create_index("ix_debate_status_lease", "debate", ["status", "lease_expires_at"], unique=False)
    op.drop_constraint("fk_debate_user_id_user", "debate", type_="foreignkey")
    op.drop_constraint("fk_debate_team_id_team", "debate", type_="foreignkey")
    op.create_foreign_key(None, "debate", "user", ["user_id"], ["id"])
    op.create_foreign_key(None, "debate", "team", ["team_id"], ["id"])
    op.drop_index("ix_debate_checkpoint_last_checkpoint_at", table_name="debate_checkpoint")
    op.drop_index("ix_debate_checkpoint_status_last_checkpoint", table_name="debate_checkpoint")
    op.create_index("ix_debate_checkpoint_last_checkpoint", "debate_checkpoint", ["last_checkpoint_at"], unique=False)
    op.create_index("ix_debate_checkpoint_status_checkpoint", "debate_checkpoint", ["status", "last_checkpoint_at"], unique=False)
    op.drop_index("ix_pairwise_vote_candidate_a_candidate_b", table_name="pairwise_vote")
    op.create_index("ix_pairwise_vote_candidates", "pairwise_vote", ["candidate_a", "candidate_b"], unique=False)
    op.create_index(op.f("ix_pairwise_vote_user_id"), "pairwise_vote", ["user_id"], unique=False)
    op.alter_column("promotions", "id",
               existing_type=sa.VARCHAR(length=36),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.alter_column("promotions", "location",
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column("promotions", "title",
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column("promotions", "body",
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column("promotions", "cta_label",
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column("promotions", "cta_url",
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column("promotions", "target_plan_slug",
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.drop_index("ix_promotions_location_priority", table_name="promotions")
    op.create_index(op.f("ix_promotions_location"), "promotions", ["location"], unique=False)
    op.add_column("user", sa.Column("plan", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False))
    op.add_column("user", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("user", sa.Column("analytics_opt_out", sa.Boolean(), nullable=False))
    op.create_index(op.f("ix_user_deleted_at"), "user", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_user_plan"), "user", ["plan"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_plan"), table_name="user")
    op.drop_index(op.f("ix_user_deleted_at"), table_name="user")
    op.drop_column("user", "analytics_opt_out")
    op.drop_column("user", "deleted_at")
    op.drop_column("user", "plan")
    op.drop_index(op.f("ix_promotions_location"), table_name="promotions")
    op.create_index("ix_promotions_location_priority", "promotions", ["location", "is_active", "priority"], unique=False)
    op.alter_column("promotions", "target_plan_slug",
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column("promotions", "cta_url",
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column("promotions", "cta_label",
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column("promotions", "body",
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column("promotions", "title",
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column("promotions", "location",
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column("promotions", "id",
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.drop_index(op.f("ix_pairwise_vote_user_id"), table_name="pairwise_vote")
    op.drop_index("ix_pairwise_vote_candidates", table_name="pairwise_vote")
    op.create_index("ix_pairwise_vote_candidate_a_candidate_b", "pairwise_vote", ["candidate_a", "candidate_b"], unique=False)
    op.drop_index("ix_debate_checkpoint_status_checkpoint", table_name="debate_checkpoint")
    op.drop_index("ix_debate_checkpoint_last_checkpoint", table_name="debate_checkpoint")
    op.create_index("ix_debate_checkpoint_status_last_checkpoint", "debate_checkpoint", ["status", "last_checkpoint_at"], unique=False)
    op.create_index("ix_debate_checkpoint_last_checkpoint_at", "debate_checkpoint", ["last_checkpoint_at"], unique=False)
    op.drop_constraint(None, "debate", type_="foreignkey")
    op.drop_constraint(None, "debate", type_="foreignkey")
    op.create_foreign_key("fk_debate_team_id_team", "debate", "team", ["team_id"], ["id"], ondelete="SET NULL")
    op.create_foreign_key("fk_debate_user_id_user", "debate", "user", ["user_id"], ["id"], ondelete="SET NULL")
    op.drop_index("ix_debate_status_lease", table_name="debate")
    op.drop_index(op.f("ix_debate_runner_id"), table_name="debate")
    op.drop_column("debate", "run_attempt")
    op.drop_column("debate", "last_heartbeat_at")
    op.drop_column("debate", "lease_expires_at")
    op.drop_column("debate", "runner_id")
    op.alter_column("billing_usage", "tokens_used",
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               existing_server_default=sa.text("0"))
    op.alter_column("billing_usage", "id",
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column("billing_subscriptions", "plan_id",
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column("billing_subscriptions", "id",
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.create_index("uq_billing_plans_slug", "billing_plans", ["slug"], unique=1)
    op.alter_column("billing_plans", "id",
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.drop_index(op.f("ix_debate_error_user_id"), table_name="debate_error")
    op.drop_index(op.f("ix_debate_error_status"), table_name="debate_error")
    op.drop_index(op.f("ix_debate_error_debate_id"), table_name="debate_error")
    op.drop_table("debate_error")
    op.drop_index(op.f("ix_support_note_user_id"), table_name="support_note")
    op.drop_index(op.f("ix_support_note_author_id"), table_name="support_note")
    op.drop_table("support_note")
    op.drop_index(op.f("ix_admin_event_trace_id"), table_name="admin_event")
    op.drop_index(op.f("ix_admin_event_level"), table_name="admin_event")
    op.drop_index(op.f("ix_admin_event_debate_id"), table_name="admin_event")
    op.drop_index("ix_admin_event_created_at", table_name="admin_event")
    op.drop_table("admin_event")
    # ### end Alembic commands ###
