"""add indexes

Revision ID: b57f4150d278
Revises: bb2c5d45d274
Create Date: 2025-11-11 09:02:31.800905

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b57f4150d278"
down_revision: Union[str, None] = "bb2c5d45d274"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_debate_created_at"), "debate", ["created_at"], unique=False)
    op.create_index(op.f("ix_debate_status"), "debate", ["status"], unique=False)
    op.create_index(op.f("ix_debate_updated_at"), "debate", ["updated_at"], unique=False)
    op.create_index(op.f("ix_debateround_debate_id"), "debateround", ["debate_id"], unique=False)
    op.create_index(op.f("ix_debateround_ended_at"), "debateround", ["ended_at"], unique=False)
    op.create_index(op.f("ix_debateround_started_at"), "debateround", ["started_at"], unique=False)
    op.create_index("ix_round_debate_index", "debateround", ["debate_id", "index"], unique=False)
    op.create_index(op.f("ix_message_created_at"), "message", ["created_at"], unique=False)
    op.create_index(op.f("ix_message_debate_id"), "message", ["debate_id"], unique=False)
    op.create_index("ix_message_debate_round", "message", ["debate_id", "round_index"], unique=False)
    op.create_index(op.f("ix_message_round_index"), "message", ["round_index"], unique=False)
    op.create_index(op.f("ix_score_created_at"), "score", ["created_at"], unique=False)
    op.create_index(op.f("ix_score_debate_id"), "score", ["debate_id"], unique=False)
    op.create_index("ix_score_debate_persona", "score", ["debate_id", "persona"], unique=False)
    op.create_index(op.f("ix_score_judge"), "score", ["judge"], unique=False)
    op.create_index(op.f("ix_score_persona"), "score", ["persona"], unique=False)
    op.create_index(op.f("ix_score_score"), "score", ["score"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_score_score"), table_name="score")
    op.drop_index(op.f("ix_score_persona"), table_name="score")
    op.drop_index(op.f("ix_score_judge"), table_name="score")
    op.drop_index("ix_score_debate_persona", table_name="score")
    op.drop_index(op.f("ix_score_debate_id"), table_name="score")
    op.drop_index(op.f("ix_score_created_at"), table_name="score")
    op.drop_index(op.f("ix_message_round_index"), table_name="message")
    op.drop_index("ix_message_debate_round", table_name="message")
    op.drop_index(op.f("ix_message_debate_id"), table_name="message")
    op.drop_index(op.f("ix_message_created_at"), table_name="message")
    op.drop_index("ix_round_debate_index", table_name="debateround")
    op.drop_index(op.f("ix_debateround_started_at"), table_name="debateround")
    op.drop_index(op.f("ix_debateround_ended_at"), table_name="debateround")
    op.drop_index(op.f("ix_debateround_debate_id"), table_name="debateround")
    op.drop_index(op.f("ix_debate_updated_at"), table_name="debate")
    op.drop_index(op.f("ix_debate_status"), table_name="debate")
    op.drop_index(op.f("ix_debate_created_at"), table_name="debate")
    # ### end Alembic commands ###
