"""add votes table

Revision ID: cdb8cc8aa732
Revises: b57f4150d278
Create Date: 2025-11-11 09:14:45.444536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cdb8cc8aa732'
down_revision: Union[str, None] = 'b57f4150d278'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('debate_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('method', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rankings', sa.JSON(), nullable=False),
    sa.Column('weights', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['debate_id'], ['debate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vote_created_at'), 'vote', ['created_at'], unique=False)
    op.create_index(op.f('ix_vote_debate_id'), 'vote', ['debate_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vote_debate_id'), table_name='vote')
    op.drop_index(op.f('ix_vote_created_at'), table_name='vote')
    op.drop_table('vote')
    # ### end Alembic commands ###
