"""Add mode to debate

Revision ID: dcdade8ec015
Revises: f65412886a02
Create Date: 2025-12-06 06:23:33.131497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dcdade8ec015'
down_revision: Union[str, None] = 'f65412886a02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('billing_plans', 'id',
    #            existing_type=sa.VARCHAR(length=36),
    #            type_=sa.Uuid(),
    #            existing_nullable=False)
    # op.drop_index('uq_billing_plans_slug', table_name='billing_plans')
    # op.alter_column('billing_subscriptions', 'id',
    #            existing_type=sa.VARCHAR(length=36),
    #            type_=sa.Uuid(),
    #            existing_nullable=False)
    # op.alter_column('billing_subscriptions', 'plan_id',
    #            existing_type=sa.VARCHAR(length=36),
    #            type_=sa.Uuid(),
    #            existing_nullable=False)
    # op.alter_column('billing_usage', 'id',
    #            existing_type=sa.VARCHAR(length=36),
    #            type_=sa.Uuid(),
    #            existing_nullable=False)
    # op.alter_column('billing_usage', 'tokens_used',
    #            existing_type=sa.BIGINT(),
    #            type_=sa.Integer(),
    #            existing_nullable=False,
    #            existing_server_default=sa.text('0'))
    op.add_column('debate', sa.Column('mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='debate'))
    op.create_index(op.f('ix_debate_mode'), 'debate', ['mode'], unique=False)
    # op.drop_index('ix_pairwise_vote_candidate_a_candidate_b', table_name='pairwise_vote')
    # op.create_index('ix_pairwise_vote_candidates', 'pairwise_vote', ['candidate_a', 'candidate_b'], unique=False)
    # op.create_index(op.f('ix_pairwise_vote_user_id'), 'pairwise_vote', ['user_id'], unique=False)
    # op.alter_column('promotions', 'id',
    #            existing_type=sa.VARCHAR(length=36),
    #            type_=sa.Uuid(),
    #            existing_nullable=False)
    # op.alter_column('promotions', 'location',
    #            existing_type=sa.TEXT(),
    #            type_=sqlmodel.sql.sqltypes.AutoString(),
    #            existing_nullable=False)
    # op.alter_column('promotions', 'title',
    #            existing_type=sa.TEXT(),
    #            type_=sqlmodel.sql.sqltypes.AutoString(),
    #            existing_nullable=False)
    # op.alter_column('promotions', 'body',
    #            existing_type=sa.TEXT(),
    #            type_=sqlmodel.sql.sqltypes.AutoString(),
    #            existing_nullable=False)
    # op.alter_column('promotions', 'cta_label',
    #            existing_type=sa.TEXT(),
    #            type_=sqlmodel.sql.sqltypes.AutoString(),
    #            existing_nullable=True)
    # op.alter_column('promotions', 'cta_url',
    #            existing_type=sa.TEXT(),
    #            type_=sqlmodel.sql.sqltypes.AutoString(),
    #            existing_nullable=True)
    # op.alter_column('promotions', 'target_plan_slug',
    #            existing_type=sa.TEXT(),
    #            type_=sqlmodel.sql.sqltypes.AutoString(),
    #            existing_nullable=True)
    # op.drop_index('ix_promotions_location_priority', table_name='promotions')
    # op.create_index(op.f('ix_promotions_location'), 'promotions', ['location'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_promotions_location'), table_name='promotions')
    op.create_index('ix_promotions_location_priority', 'promotions', ['location', 'is_active', 'priority'], unique=False)
    op.alter_column('promotions', 'target_plan_slug',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('promotions', 'cta_url',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('promotions', 'cta_label',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('promotions', 'body',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('promotions', 'title',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('promotions', 'location',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('promotions', 'id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.drop_index(op.f('ix_pairwise_vote_user_id'), table_name='pairwise_vote')
    op.drop_index('ix_pairwise_vote_candidates', table_name='pairwise_vote')
    op.create_index('ix_pairwise_vote_candidate_a_candidate_b', 'pairwise_vote', ['candidate_a', 'candidate_b'], unique=False)
    op.drop_index(op.f('ix_debate_mode'), table_name='debate')
    op.drop_column('debate', 'mode')
    op.alter_column('billing_usage', 'tokens_used',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('billing_usage', 'id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('billing_subscriptions', 'plan_id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('billing_subscriptions', 'id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.create_index('uq_billing_plans_slug', 'billing_plans', ['slug'], unique=1)
    op.alter_column('billing_plans', 'id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    # ### end Alembic commands ###
