"""Add routing columns to Debate

Revision ID: e2612470e38a
Revises: 40eb9d7aa097
Create Date: 2025-11-26 13:58:15.388001

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e2612470e38a"
down_revision: Union[str, None] = "40eb9d7aa097"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("billing_plans", schema=None) as batch_op:
        batch_op.alter_column("slug",
                   existing_type=sa.TEXT(),
                   type_=sqlmodel.sql.sqltypes.AutoString(),
                   existing_nullable=False)
        batch_op.alter_column("name",
                   existing_type=sa.TEXT(),
                   type_=sqlmodel.sql.sqltypes.AutoString(),
                   existing_nullable=False)
        batch_op.alter_column("currency",
                   existing_type=sa.TEXT(),
                   type_=sqlmodel.sql.sqltypes.AutoString(),
                   existing_nullable=False,
                   existing_server_default=sa.text("'USD'::text"))
        batch_op.alter_column("limits",
                   existing_type=postgresql.JSONB(astext_type=sa.Text()),
                   type_=sa.JSON(),
                   existing_nullable=False,
                   existing_server_default=sa.text("'{}'::jsonb"))
        # batch_op.drop_index('uq_billing_plans_default_free')
        # batch_op.drop_index('uq_billing_plans_slug')
    
    # op.drop_index('uq_billing_plans_default_free', table_name='billing_plans')
    # op.drop_index('uq_billing_plans_slug', table_name='billing_plans')
    op.create_index(op.f("ix_billing_plans_slug"), "billing_plans", ["slug"], unique=True)

    with op.batch_alter_table("billing_subscriptions", schema=None) as batch_op:
        batch_op.alter_column("status",
                   existing_type=sa.TEXT(),
                   type_=sqlmodel.sql.sqltypes.AutoString(),
                   existing_nullable=False)
        batch_op.alter_column("provider",
                   existing_type=sa.TEXT(),
                   type_=sqlmodel.sql.sqltypes.AutoString(),
                   existing_nullable=False)
        batch_op.alter_column("provider_customer_id",
                   existing_type=sa.TEXT(),
                   type_=sqlmodel.sql.sqltypes.AutoString(),
                   existing_nullable=True)
        batch_op.alter_column("provider_subscription_id",
                   existing_type=sa.TEXT(),
                   type_=sqlmodel.sql.sqltypes.AutoString(),
                   existing_nullable=True)
        # batch_op.drop_constraint('billing_subscriptions_plan_id_fkey', type_='foreignkey')
        # batch_op.drop_constraint('billing_subscriptions_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key("fk_billing_subscriptions_plan_id_billing_plans", "billing_plans", ["plan_id"], ["id"])
        batch_op.create_foreign_key("fk_billing_subscriptions_user_id_user", "user", ["user_id"], ["id"])
    
    op.drop_index("ix_billing_subscriptions_provider_ref", table_name="billing_subscriptions")

    with op.batch_alter_table("billing_usage", schema=None) as batch_op:
        # ... (lines 71-83)
        # batch_op.drop_constraint('billing_usage_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key("fk_billing_usage_user_id_user", "user", ["user_id"], ["id"])

    op.drop_index("ix_billing_usage_user_period", table_name="billing_usage")
    op.create_index(op.f("ix_billing_usage_period"), "billing_usage", ["period"], unique=False)
    op.create_index(op.f("ix_billing_usage_user_id"), "billing_usage", ["user_id"], unique=False)

    with op.batch_alter_table("debate", schema=None) as batch_op:
        batch_op.alter_column("engine_version",
                   existing_type=sa.VARCHAR(length=64),
                   type_=sa.Text(),
                   existing_nullable=True)
        # NOTE: FK constraints may already exist from earlier migrations - skip if so
        # batch_op.drop_constraint('fk_debate_user_id_user', type_='foreignkey')
        # batch_op.drop_constraint('fk_debate_team_id_team', type_='foreignkey')
        # batch_op.create_foreign_key("fk_debate_team_id_team", "team", ["team_id"], ["id"])
        # batch_op.create_foreign_key("fk_debate_user_id_user", "user", ["user_id"], ["id"])
    
    op.add_column("debate", sa.Column("model_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column("debate", sa.Column("routed_model", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column("debate", sa.Column("routing_policy", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column("debate", sa.Column("routing_meta", sa.JSON(), nullable=True))
    
    op.create_index(op.f("ix_debate_model_id"), "debate", ["model_id"], unique=False)
    op.create_index(op.f("ix_debate_routed_model"), "debate", ["routed_model"], unique=False)

    # ... (pairwise_vote and promotions sections)

    with op.batch_alter_table("team_member", schema=None) as batch_op:
        # batch_op.drop_constraint('team_member_user_id_fkey', type_='foreignkey')
        # batch_op.drop_constraint('team_member_team_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key("fk_team_member_user_id_user", "user", ["user_id"], ["id"])
        batch_op.create_foreign_key("fk_team_member_team_id_team", "team", ["team_id"], ["id"])

    # with op.batch_alter_table('usage_counter', schema=None) as batch_op:
    op.create_index(op.f("ix_usage_counter_period"), "usage_counter", ["period"], unique=False)
    op.create_index(op.f("ix_usage_counter_user_id"), "usage_counter", ["user_id"], unique=False)

    # with op.batch_alter_table('usage_quota', schema=None) as batch_op:
    op.create_index(op.f("ix_usage_quota_period"), "usage_quota", ["period"], unique=False)
    op.create_index(op.f("ix_usage_quota_user_id"), "usage_quota", ["user_id"], unique=False)

    # with op.batch_alter_table('vote', schema=None) as batch_op:
    op.create_index("ix_vote_created_at", "vote", ["created_at"], unique=False)
    op.create_index(op.f("ix_vote_debate_id"), "vote", ["debate_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_vote_debate_id"), table_name="vote")
    op.drop_index("ix_vote_created_at", table_name="vote")
    op.drop_index(op.f("ix_usage_quota_user_id"), table_name="usage_quota")
    op.drop_index(op.f("ix_usage_quota_period"), table_name="usage_quota")
    op.drop_index(op.f("ix_usage_counter_user_id"), table_name="usage_counter")
    op.drop_index(op.f("ix_usage_counter_period"), table_name="usage_counter")
    op.drop_constraint(None, "team_member", type_="foreignkey")
    op.drop_constraint(None, "team_member", type_="foreignkey")
    op.create_foreign_key("team_member_team_id_fkey", "team_member", "team", ["team_id"], ["id"], ondelete="CASCADE")
    op.create_foreign_key("team_member_user_id_fkey", "team_member", "user", ["user_id"], ["id"], ondelete="CASCADE")
    op.drop_index(op.f("ix_promotions_location"), table_name="promotions")
    op.create_index("ix_promotions_location_priority", "promotions", ["location", "is_active", "priority"], unique=False)
    op.alter_column("promotions", "target_plan_slug",
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column("promotions", "cta_url",
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column("promotions", "cta_label",
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column("promotions", "body",
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column("promotions", "title",
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column("promotions", "location",
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f("ix_pairwise_vote_user_id"), table_name="pairwise_vote")
    op.drop_index("ix_pairwise_vote_candidates", table_name="pairwise_vote")
    op.create_index("ix_pairwise_vote_candidate_a_candidate_b", "pairwise_vote", ["candidate_a", "candidate_b"], unique=False)
    op.drop_constraint(None, "debate", type_="foreignkey")
    op.drop_constraint(None, "debate", type_="foreignkey")
    op.create_foreign_key("fk_debate_team_id_team", "debate", "team", ["team_id"], ["id"], ondelete="SET NULL")
    op.create_foreign_key("fk_debate_user_id_user", "debate", "user", ["user_id"], ["id"], ondelete="SET NULL")
    op.drop_index(op.f("ix_debate_routed_model"), table_name="debate")
    op.drop_index(op.f("ix_debate_model_id"), table_name="debate")
    op.alter_column("debate", "engine_version",
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
    op.drop_column("debate", "routing_meta")
    op.drop_column("debate", "routing_policy")
    op.drop_column("debate", "routed_model")
    op.drop_column("debate", "model_id")
    op.drop_constraint(None, "billing_usage", type_="foreignkey")
    op.create_foreign_key("billing_usage_user_id_fkey", "billing_usage", "user", ["user_id"], ["id"], ondelete="CASCADE")
    op.drop_index(op.f("ix_billing_usage_user_id"), table_name="billing_usage")
    op.drop_index(op.f("ix_billing_usage_period"), table_name="billing_usage")
    op.create_index("ix_billing_usage_user_period", "billing_usage", ["user_id", "period"], unique=False)
    op.alter_column("billing_usage", "model_tokens",
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column("billing_usage", "tokens_used",
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               existing_server_default=sa.text("0"))
    op.drop_constraint(None, "billing_subscriptions", type_="foreignkey")
    op.drop_constraint(None, "billing_subscriptions", type_="foreignkey")
    op.create_foreign_key("billing_subscriptions_user_id_fkey", "billing_subscriptions", "user", ["user_id"], ["id"], ondelete="CASCADE")
    op.create_foreign_key("billing_subscriptions_plan_id_fkey", "billing_subscriptions", "billing_plans", ["plan_id"], ["id"], ondelete="CASCADE")
    op.create_index("ix_billing_subscriptions_provider_ref", "billing_subscriptions", ["provider", "provider_subscription_id"], unique=False)
    op.alter_column("billing_subscriptions", "provider_subscription_id",
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column("billing_subscriptions", "provider_customer_id",
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column("billing_subscriptions", "provider",
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column("billing_subscriptions", "status",
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f("ix_billing_plans_slug"), table_name="billing_plans")
    op.create_index("uq_billing_plans_slug", "billing_plans", ["slug"], unique=True)
    op.create_index("uq_billing_plans_default_free", "billing_plans", ["is_default_free"], unique=True, postgresql_where="(is_default_free = true)")
    op.alter_column("billing_plans", "limits",
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column("billing_plans", "currency",
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'USD'::text"))
    op.alter_column("billing_plans", "name",
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column("billing_plans", "slug",
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
